return {
	Settings = {
		MusicVolume = 1,
		SfxVolume = 1,
		VfxQuality = 1,
		VfxRenderDistance = 1,
		ScreenShakeEnabled = true,
	},

	Keybinds = {
		Hotbar = {
			[1] = "One",
			[2] = "Two",
			[3] = "Three",
			[4] = "Four",
			[5] = "Five",
			[6] = "Six",
			[7] = "Seven",
			[8] = "Eight",
			[9] = "Nine",
			[10] = "Zero",
		},
		UI = {
			Inventory = "Tab",
		},
	},

	Inventory = {
		Backpack = {},
		Hotbar = {
			[1] = { ItemId = "IronSword", Quantity = 1, Info = { Durability = 100 } },
			[2] = { ItemId = "HealthPotion", Quantity = 5, Info = {} },
		},
		Bank = {},
	},

	Currency = 0,
	Stats = {},
}